version: '3.9'
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pagosdb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./database/init_data_base.sql:/docker-entrypoint-initdb.d/init_data_base.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: pagosdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started

